### ISSUE TITLE
gitclone issue 0.1.5 - can't seem to clone a repo

### ISSUE THREAD

**Issue by imaginethepoet** [rubenv/grunt-git#16]
I've gone over the usage instructions several times now just to make sure I'm not missing something. 

I'm not sure if this bug has popped back up again. I'm running 0.1.5 and have not been able to clone a repo. I'm using my own repo as a test: This is my coffeescript task below. I apologize if I'm just missing something.

```
gitclone:
  clone:
    options:
      repo: 'https://github.com/imaginethepoet/autojqm'
      branch: 'master'
      directory: "repo"
```

error:
gitclone tasks require that you specify a "repository"
